---
title: "Salmon Biphasic Growth and Fecundity  model"
author: "Viktor Thunell" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    page-layout: full
    embed-resources: true
    toc: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 80%
editor: source
execute: 
  echo: true
  eval: true
  cache: true
---

## Load libraries

```{r libs}
#| message: false
#| warning: false
#| cache: false

# Load libraries, install if needed
pkgs <- c("tidyverse", "tidylog", "devtools","viridis","nls.multstart", "broom", "patchwork", "coda", "boot", "tidybayes","bayesplot", "nimble", "here", "purrr")

# remotes::install_github("nimble-dev/nimble", ref = "devel", subdir = "packages/nimble")

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){
    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  }

invisible(lapply(pkgs, library, character.only = T))

options(ggplot2.continuous.colour = "viridis")
theme_set(theme_light()) # check why global theme option not working when rendering
# Set path
color_scheme_set("viridis")
home <- here::here()
```

## Read data

```{r}
#| message: false
#| warning: false
#| cache: false
#set.seed(123)
## Read data
sallaa <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-laa_2025-09-08.RData")) %>%
  rename(year = fi_year,
         site = sai_location,
         sea.age = sea_age_year,
         juv.age = juvenile_age_year,
         tot.age = tot_age_year,
         lat = fisa_y_4326,
         lon = fisa_x_4326) %>%
  #filter out tot.age = 0 individuals
  filter(!(sea.age == 0 & juv.age == 0)) %>%
  #filter out non-aged individuals (~90000 individuals)
  filter(!(is.na(sea.age) & is.na(juv.age))) %>%
  # removes smolt.age = 0:
  filter(!(age.type == "both" & juv.age == 0)) %>%
  mutate(hatch.year = year-tot.age) %>% # to filter data based o hatch year instead of year to predict growth pars before catch year
  filter(#!is.na(juv.age), # removes age.type = "sea.only"
         !is.na(year),
         hatch.year > 1997)
  
# Fecundity  
salfec <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-fec_2025-09-08.RData"))

# sallaa %>%
#   summarise(n(), .by = c(sex,age.type))
# data %>%
#   summarise(n(), .by = c(sex,age.type,smo.age))

# if we estimate smo.age to be < age for juveniles, the sex will be aprt of the length prediction. 
```

## Plot data
```{r plot dat}
sallaa %>%
  drop_na(sex) %>%
  ggplot(aes(tot.age, length_mm, color = sex)) +
  geom_point() +
  facet_grid(age.type~sex) +
  scale_x_continuous(breaks = seq(0, 13, 1) ) +
  theme_light() 

# If dropping all inds where both sea and sm age is NA
sallaa %>% 
  ggplot() +
  geom_density(aes(x = tot.age), fill = "deeppink", alpha = 0.5) +
  xlim(0, 13) +

sallaa %>% 
  ggplot() + 
  geom_density(aes(x = length_mm), fill = "deeppink", alpha = 0.5)

sallaa %>% 
  drop_na(sea.age,sex) %>%
  ggplot() +
  geom_density(aes(x = length_mm, fill = factor(sex)), alpha = 0.5) +
  facet_wrap(~tot.age)

# age at smoltification by spatial unit
sallaa %>%
  filter(age.type == "both") %>%
  ggplot() +
  geom_density(aes(x = juv.age, color = spat.unit),  alpha = 0.5) +
  facet_wrap(~spat.unit) +
  xlim(-1, 5)

# juvenile size at age
sallaa %>%
  filter(age.type == "juve.only") %>%
  ggplot(aes(x = juv.age, y =length_mm, color = spat.unit)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = lm) +
  facet_wrap(~spat.unit)

# size at age zero
sallaa %>%
  filter(juv.age == 0) %>%
  ggplot() +
  geom_density(aes(x = length_mm), fill = "deeppink", alpha = 0.5) +
  labs(title = "Age 0")
  
data.biph %>%
  filter(age.type == "both") %>%
  ggplot(aes(tot.age, length_mm, color = spat.unit)) +
  geom_point() +
  facet_grid(~spat.unit) +
  scale_x_continuous(breaks = seq(0, 13, 1) ) +
  theme_light() 

```

## Source model / Load samples
```{r}
# t <- Sys.time()
# source(file = paste0(home,"/R/model devel/2-2_model_salmon_biphasic6.R"))
# Sys.time() - t
# 
# t <- Sys.time()
# source(file = paste0(home,"/R/model devel/2-2_model_salmon_fecundity_v1.R"))
# Sys.time() - t

biph.samples <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/biph9_samples_1025.RData")
#b.samples <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/biph8_samples_50_1023.RData")
# get fecundity paramters
fec.dpars <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/fec_dpars.RData")
#fec.samples <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/fec_samples_1023.RData")

data.fec <- salfec %>%
  mutate(su = as.integer(factor(spat.unit))) %>%
  drop_na(su)

# add in a and b to missing su:s and make fex.dpars su:s equal biph su:s
fec.dpars2 <- fec.dpars %>%
  left_join(data.fec %>% distinct(spat.unit,su)) %>%
  filter(spat.unit %in% unique(data.biph$spat.unit)) %>%
  select(-su) 
  
fec.dpars <- fec.dpars2 %>%
  bind_rows(data.biph %>% distinct(spat.unit) %>% filter(!spat.unit %in% data.fec$spat.unit) ) %>%
  mutate(mufb = if_else(is.na(mufb),mean(fec.dpars$mufb),mufb),
         sdfb = if_else(is.na(sdfb),mean(fec.dpars$sdfb),sdfb),
         #hfa  = ma^2 / va, rafa   = ma / va
         shfa = if_else(is.na(shfa),
                        mean(fec.dpars$ma)^2 / mean(fec.dpars$va),shfa),
         rafa = if_else(is.na(rafa), mean(fec.dpars$ma)/ mean(fec.dpars$va),rafa))

```

## Calculate WAIC
```{r}

#biph6.waic <- calculateWAIC(biph6.samples, biph6.model)
```

## Trace plots 
```{r check bpars}
samples <- biph05.samples
#samples <- mcmc.list(lapply(samples, as.mcmc))

node.sub <- grep("^g\\[", colnames(samples[[1]]), value = TRUE)
samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE] %>%
  mcmc_trace()

# node.sub <- grep("^par\\[", colnames(samples), value = TRUE)
# samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE] %>%
#   mcmc_trace()

node.sub <- grep("^k.year\\[", colnames(samples[[1]]), value = TRUE)
samples[, node.sub[sample(1:length(node.sub), 36)], drop = FALSE] %>%
  mcmc_trace()

node.sub <- grep("^linf\\[", colnames(samples[[1]]), value = TRUE)
samples[, node.sub[], drop = FALSE] %>%
  mcmc_trace()

node.sub <- grep("^lb.mu\\[", colnames(samples[[1]]), value = TRUE)
mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE])

node.sub <- grep("^Ustar\\[", colnames(samples[[1]]), value = TRUE)
mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 36)], drop = FALSE])

node.sub <- grep("sig.l", colnames(samples[[1]]), value = TRUE)
mcmc_trace(samples[, node.sub, drop = FALSE])

#hmmm
node.sub <- grep("smo.age", colnames(samples), value = TRUE)
mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE])

node.sub <- grep("smp", colnames(samples), value = TRUE)
mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE])

# l.mu has NAs (for age beyond catch age)
node.subt <- colnames(samples[[1]])[colSums(is.na(samples[[1]])) == 0]
node.sub <- grep("^l.mu\\[", node.subt, value = TRUE)
mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 24)], drop = FALSE])

# node.sub <- grep("^f.mu\\[", node.subt, value = TRUE)
# mcmc_trace(samples[, node.sub[sample(1:length(node.sub), 10)], drop = FALSE])

```

## Sample distributions

```{r}
# retrieve names for plotting
su.labs <- sallaa %>%
  mutate(spat.unit.int = as.integer(factor(spat.unit))) %>%
  distinct(spat.unit.int, spat.unit) %>%
  rename(su = spat.unit.int) 
su.labs <- su.labs %>%
  bind_rows(su.labs %>% mutate(su = su+nsu)) %>%
  { setNames(.$spat.unit, .$su) }

hy.labs <- data %>%
  distinct(hatch.year, hatch.year.f) %>%
  rename(hy = hatch.year.f) %>%
  #deframe()
  { setNames(.$hatch.year, .$hy) }
```

### g, lb.mu
```{r plot bpars}
# lb.mu[spat.unit]
samples %>%
  gather_draws(lb.mu[su], sep = ",") %>%
  ggplot() +
  geom_density(aes(x = .value, color = factor(su))) +
  scale_color_discrete(labels = su.labs) +
  theme_light() +
  labs(title = "lb.mu")

# g[spat.unit, hatch.year]
samples %>%
  gather_draws(g[su, hy], sep = ",") %>%
  filter(hy == c(1:5)) %>%
  ggplot() +
  geom_density(aes(x = exp(.value), color = factor(hy))) +
  scale_color_discrete(labels = hy.labs) +
  facet_wrap(~su, scales = "free", labeller = labeller(sup = su.labs)) +
  theme_light() +
  labs(title = "g, juv. growth rate")

samples %>%
  gather_draws(g[su, hy], sep = ",") %>%
  ggplot() +
  geom_boxplot(aes(x = factor(hy), y = .value),
               outlier.size = 0.5,
               outlier.alpha = 0.1) +
  scale_x_discrete(labels = hy.labs) +
  facet_wrap(~su, scales = "free", labeller = labeller(su = su.labs)) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1, size = rel(.75))) +
  labs(title = "g, juv. growth rate")
  
  # #median_qi() %>%
  # ggplot() +
  # geom_line(aes(x = hy, y = .value, color = factor(su))) +
  # geom_ribbon(aes(x = hy, ymin = .lower, ymax = .upper, fill = factor(su)), alpha = 0.3) + 
  # facet_wrap(~su) +
  # scale_color_discrete(labels = su.labs) +
  # facet_wrap(~su, scales = "free", labeller = labeller(su = su.labs)) +
  # theme_light() +
  # labs(title = "g, juv. growth rate")

data %>%
  distinct(hatch.year.f,hatch.year,year)%>%
  arrange(hatch.year)
data %>%
  distinct(year,year.f,hatch.year) %>%
  arrange(year)
min(data$hatch.year)+maxyear

max(data$hatch.year) + 
  data %>%
  filter(year == max(year)) %>%
  filter(tot.age == max(tot.age)) %>%
  distinct(tot.age) %>% pull(tot.age)
minyear <- min(data$hatch.year.f)

```

### par 1 / Linf
```{r }

samples %>%
  gather_draws(log_p.year[hy, sup], sep = ",") %>%
  filter(sup %in% 1:nsu) %>%
  ggplot() +
  geom_density(aes(x = exp(.value), color = factor(hy))) +
  scale_color_discrete(labels = hy.labs) +
  facet_wrap(~sup, scales = "free", labeller = labeller(sup = su.labs)) +
  theme_light() +
  labs("Linf")

tmp <- samples %>%
  gather_draws(log_p.year[hy, sup], sep = ",") %>%
  filter(sup %in% 1:nsu)
tmp %>%
  ggplot() +
  geom_boxplot(aes(x = factor(hy), y = exp(.value)),
               outliers = FALSE) +
  scale_x_discrete(labels = hy.labs) +
  facet_wrap(~sup, scales = "free", labeller = labeller(sup = su.labs)) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1, size = rel(.75))) +
  labs(title = "Linf")

```

### par 2 / k
```{r }
# par 2
samples %>%
  gather_draws(log_p.year[hy, sup], sep = ",") %>%
  filter(sup %in% (nsu+1):npars) %>%
  ggplot() +
  geom_density(aes(x = .value, color = factor(hy))) +
  scale_color_discrete(labels = hy.labs) +
  facet_wrap(~sup, scales = "free", labeller = labeller(sup = su.labs)) +
  theme_minimal() +
  labs("k")

tmpk <- samples %>%
  gather_draws(log_p.year[hy, sup], sep = ",") %>%
  filter(sup %in% (nsu+1):npars)
tmpk %>%
  ggplot() +
  geom_boxplot(aes(x = factor(hy), y = .value),
               outliers = FALSE) +
  scale_x_discrete(labels = hy.labs) +
  facet_wrap(~sup, scales = "free", labeller = labeller(sup = su.labs)) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1, size = rel(.75))) +
  labs(title = "k")

```

### l.mu
```{r check blmu}
#samp.lmu <- biph5.con.samp.lmu
# remove NA nodes (the older-than-catch-age nodes)
node.subt <- colnames(samples)[colSums(is.na(samples)) == 0]
node.sub <- grep("^l.mu\\[", node.subt, value = TRUE)

tmpl <- samples[, node.sub, drop = FALSE] %>%
  gather_draws(l.mu[gy,id], sep = ",") %>%
  left_join(data %>% select(ind.id,spat.unit,hatch.year,age.type,site), join_by(id == ind.id)) %>%
  rename(su = spat.unit)

# plot density by growth curve
tmpl %>%
  ungroup(id) %>% # to summarise over gy only
  ggplot() +
  geom_boxplot(aes(x = factor(gy), y = .value, color = age.type),
               outlier.shape = NA,
               #outlier.alpha = 0.1
               )# +
  facet_wrap(~su, labeller = labeller(su = su.labs))
  geom_point(data = data, aes(x = tot.age.dec, y = length_mm, color = spat.unit), alpha = 0.1)
  
  

```



```{r check blmu}
# plot observed against predicted
obs <- data %>%
  select(length_mm,tot.age,ind.id,spat.unit) %>%
  mutate(tot.age = round(tot.age),
         observed = length_mm)

dataNodes <- biph5.con.model$getNodeNames(dataOnly = TRUE)
  parentNodes <- biph5.con.model$getParents(dataNodes, stochOnly = TRUE)       #all of these should be added to monitor below to recreate other model variables...
  stnodes <- biph5.con.model$getNodeNames(stochOnly = TRUE, includeData = FALSE)
  allvars<-biph5.con.model$getVarNames(nodes = stnodes)
  mvars<-allvars[!(grepl("lifted",allvars))]  
gc()
predi <- samp.cl[,1:3000] %>%
  gather_draws(l.mu[age.i,ind.id], sep = ",") %>%
  median_qi() %>%
  rename(predicted = .value) %>%
  #mutate(tot.age = age.i-1) %>%
  filter(tot.age %in% obs$tot.age & ind.id %in% obs$ind.id)

plusg.po <- predi %>%
  left_join(obs, by = join_by(tot.age, ind.id)) %>%
  drop_na(observed) %>%
  ggplot(aes(x = observed, y = predicted, color = factor(spat.unit))) +
  geom_point(size = 2, alpha = 0.5) +
  geom_errorbar(aes(ymin = .lower, ymax = .upper), width = 0.2, alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  theme_minimal() +
  ylim(0,1300) +
  xlim(0,1300) 

predi %>%
  left_join(obs, by = join_by(tot.age, ind.id)) %>%
  #drop_na(observed) %>%
  mutate(op.rat = if_else(is.na(observed), NA, observed/predicted)) %>%
  #filter(op.rat < 0.5 | is.na(op.rat)) %>%
  filter(op.rat < 0.5) %>%
  #arrange(factor(ind.id))
  pull(ind.id) %>% 
  sallaa[.,]

predi %>%
  left_join(obs, by = join_by(tot.age, ind.id)) %>%
  group_by(ind.id) %>%
  mutate(spat.unit = ifelse(is.na(spat.unit), first(na.omit(spat.unit)), spat.unit)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(tot.age, predicted, color = ind.id, group = ind.id)) +
  geom_point(aes(tot.age, observed, color = ind.id, group = ind.id), alpha = 0.2) +
  facet_wrap(~spat.unit)

```

### smolt ages
```{r }
data %>%
  filter(!is.na(smo.age)) %>%
  select(smo.age) %>%
  mutate(t = "obs") %>%
  bind_rows( biph5.con.samp.smo %>% gather_draws(smo.age[i]) %>% rename(smo.age = .value) %>% mutate(t = "pred")) %>%
  ggplot() +
  geom_density(aes(smo.age, fill = t))
```


## l.mu and Fecundity over time

### l.mu

```{r}
# Function for calculating l.mu
calc_l_mu <- nimbleFunction(
  run = function(
    lb_mu = double(1), 
    g = double(2), 
    log_p_year = double(2),
    su = double(1),
    age = double(1),
    smo_age = double(1),
    hatch_year_f = double(1),
    growth_year = double(1),
    doy_dec = double(1),
    max_age = double(0)
  ) {
    returnType(double(2))
    
    nind <- length(su)
    nyears <- dim(g)[1]
    nsu <- dim(g)[2]
    
    # initialize output with sentinel (-999)
    l_mu <- matrix(-999, nrow = max_age + 1, ncol = nind)
    
    for (i in 1:nind) {
      su_i <- su[i]
      hyf_i <- hatch_year_f[i]
      ag_i <- age[i]
      smo_i <- smo_age[i]
      gy_i <- growth_year[i]
      doy_i <- doy_dec[i]
      
      # initial 0+ prediction
      l_prev <- lb_mu[su_i] +
        (1.0 - step(1.0 - (ag_i + 0.001))) *
        (exp(g[hyf_i, su_i]) + step(1.0 - (ag_i + 0.001)) * exp(g[hyf_i, su_i]) * doy_i)
      
      l_mu[1, i] <- l_prev
      
      if (gy_i >= 1) {
        for (a in 2:(gy_i + 1)) {
          year_idx <- hyf_i + (a - 1)
          outside <- step(1.0 - year_idx) + step(year_idx - nyears)
          
          if (outside == 0.0) {
            pre_smolt <- step(smo_i - (a - 0.999))
            post_smolt <- 1.0 - pre_smolt
            before_age <- 1.0 - step((a - 1) - (ag_i + 0.001))
            
            g_exp <- exp(g[year_idx, su_i])
            linf_exp <- exp(log_p_year[year_idx, su_i])
            k_exp <- exp(log_p_year[year_idx, nsu + su_i])
            
            delta_len <- before_age * (
              pre_smolt * g_exp +
                post_smolt * ((linf_exp - l_prev) * (1.0 - exp(-k_exp)))
            ) +
              (1.0 - before_age) * (
                pre_smolt * g_exp * doy_i +
                  post_smolt * ((linf_exp - l_prev) * (1.0 - exp(-k_exp * doy_i)))
              )
            
            l_new <- l_prev + delta_len
            l_prev <- l_new
            l_mu[a, i] <- l_new
          } else {
            l_mu[a, i] <- l_prev
          }
        } # end loop a
      } # end if gy_i >= 1
    } # end loop i
    
    return(l_mu)
  }
)

recompute_lmu <- function(samples, consts, calc_l_mu_c, n_draws) {
  message("Preparing to recompute l.mu from posterior samples...")

  nyear <- consts$nyear
  nsu   <- consts$nsu
  nobs  <- length(consts$su)
  max_age <- max(consts$growth.year, na.rm = TRUE)

  # extract parameter arrays
  lb_mu_samps <- extract_node_samples(samples, "^lb.mu\\[", c(nsu))
  g_samps     <- extract_node_samples(samples, "^g\\[", c(nyear, nsu))
  logp_samps  <- extract_node_samples(samples, "^log_p.year\\[", c(nyear, consts$npars))
  smo_age_samps <- extract_node_samples(samples, "^smo.age\\[", c(consts$nobs))

  n_draws <- min(n_draws, dim(lb_mu_samps)[1])
  message(sprintf("Running %d posterior draws...", n_draws))
  
  lmu_list <- vector("list", n_draws)
  
  for (i in seq_len(n_draws)) {
    if (i %% 50 == 0) message("  • Draw ", i, "/", n_draws)

    lb_mu_i   <- as.numeric(lb_mu_samps[i, , drop = TRUE])
    g_i       <- g_samps[i, , , drop = TRUE]
    logp_i    <- logp_samps[i, , , drop = TRUE]
    smo_age_i <- as.numeric(smo_age_samps[i, , drop = TRUE])
    
    lmu_i <- calc_l_mu_c(
      lb_mu        = lb_mu_i,
      g            = g_i,
      log_p_year   = logp_i,
      smo_age      = smo_age_i,
      su           = consts$su,
      age          = consts$age,
      hatch_year_f = consts$hatch.year.f,
      growth_year  = consts$growth.year,
      doy_dec      = consts$doy.dec,
      max_age      = max_age
    )

    # replace sentinel with NA
    lmu_i[lmu_i == -999] <- NA_real_
    lmu_list[[i]] <- lmu_i
  }

  message("Finished recomputing all deterministic l.mu values.")
  return(lmu_list)
}

extract_node_samples <- function(samples, pattern, dims) {
  cols <- grep(pattern, colnames(samples), value = TRUE)
  if (length(cols) == 0)
    stop("No columns found for pattern: ", pattern)

  arr <- as.matrix(samples[, cols, drop = FALSE])
  ndraws <- nrow(arr)
  dims <- as.integer(unlist(dims))
  ncols <- ncol(arr)
  expected <- prod(dims)

  # Handle mismatched column counts gracefully
  if (expected != ncols) {
    warning(sprintf(
      "Dimension mismatch for pattern '%s': expected %d, got %d. Adjusting dims automatically.",
      pattern, expected, ncols
    ))

    if (length(dims) == 2) {
      inferred_nyear <- ncols / dims[2]
      dims <- c(as.integer(inferred_nyear), dims[2])
    } else if (length(dims) == 3) {
      inferred_nyear <- ncols / (dims[2] * dims[3])
      dims <- c(as.integer(inferred_nyear), dims[2], dims[3])
    } else if (length(dims) == 1) {
      dims <- ncols
    }
    message(" → Inferred dims for ", pattern, ": ", paste(dims, collapse = " x "))
  }

  # Always produce an array with draw dimension first
  full_dims <- c(ndraws, dims)
  out <- array(as.numeric(arr), dim = full_dims)

  # Guarantee minimum dimension of 2 (for single-node cases)
  if (length(dim(out)) == 1) {
    dim(out) <- c(ndraws, length(cols))
  }

  return(out)
}

calc_l_mu_c <- compileNimble(calc_l_mu)
lmu_list <- recompute_lmu(as.data.frame(biph.samples), consts, calc_l_mu_c, n_draws = nrow(biph.samples))
str(lmu_list) # [years, ind.id]

```

## Option 2

```{r}

lb_mu_med <- extract_node_samples(biph.samples, "^lb.mu\\[", c(consts$nsu)) |>
  apply(2, median, na.rm = TRUE)

g_med <- extract_node_samples(biph.samples, "^g\\[", c(consts$nyear, consts$nsu)) |>
  apply(c(2, 3), median, na.rm = TRUE)

logp_med <- extract_node_samples(biph.samples, "^log_p.year\\[", c(consts$nyear, consts$npars)) |>
  apply(c(2, 3), median, na.rm = TRUE)


# Ensure correct integer smolt ages (if continuous, round)
# mean_smo_df <- mean_smo_df %>%
#   mutate(m_smo_age = round(mean_smo_age))
m_smo_df <- data.biph %>%
  summarise(msmo = median(smo.age, na.rm = TRUE), .by = su)

su_vec   <- rep(1:consts$nsu, each = consts$nyear)
year_vec <- rep(1:consts$nyear, times = consts$nsu)
nind_sim <- length(su_vec)

# Join smolt age by spatial unit
smo_age_sim <- m_smo_df$msmo[match(su_vec, m_smo_df$su)]

# Other deterministic covariates
age_sim <- 6 # arbitrary upper age (6 years) for all
growth_year_sim <- age_sim
doy_dec_sim <- 1.0  # end-of-year condition (full year of growth)
hatch_year_f_sim <- pmax(1, year_vec - growth_year_sim + 1)  # ensure valid index
max_age <- growth_year_sim

lmu_sim <- calc_l_mu_c(
  lb_mu        = lb_mu_med,
  g            = g_med,
  log_p_year   = logp_med,
  su           = su_vec,
  age          = rep(age_sim, nind_sim),
  smo_age      = smo_age_sim,
  hatch_year_f = hatch_year_f_sim,
  growth_year  = rep(growth_year_sim, nind_sim),
  doy_dec      = rep(doy_dec_sim, nind_sim),
  max_age      = max_age
)

lmu_sim[lmu_sim == -999] <- NA_real_


lmu_df <- as.data.frame(lmu_sim) |>
  mutate(age_idx = row_number()) |>
  pivot_longer(-age_idx, names_to = "ind", values_to = "length_mm") |>
  mutate(ind = as.integer(str_remove(ind, "V")),
         su = su_vec[ind],
         year = year_vec[ind],
         smo_age = smo_age_sim[ind])

lmu_df %>%
  left_join(data.biph %>% distinct(spat.unit, su)) %>%
  filter(year %in% sample(1:26,10)) %>%
  ggplot(aes(x = age_idx - 1, y = length_mm, group = interaction(spat.unit, year), color = factor(year)), show.legend = FALSE) +
  geom_line(alpha = 0.7) +
  facet_wrap(~spat.unit) +
  geom_vline(aes(xintercept = smo_age), linetype = 2, color = "grey40", alpha = 0.5) +
  labs(x = "age", y = "predicted length") +
  theme_minimal() 

# ggplot(aes(age_idx - 1, length_mm, group = ind, color = spat.unit)) +
#   
#   geom_line() +
#   #geom_vline(aes(xintercept = smo_age), linetype = 2, color = "grey50", alpha = 0.4) +
#   labs(x = "age",y = "predicted length [mm]") +
#   facet_wrap(~spat.unit) +
#   theme_minimal() +
#   theme(panel.grid = element_blank())
```

### f.mu
```{r}
compute_fmu_summary_from_lmu_df <- function(lmu_df, fec_dpars, ndraws = 2000) {
  # Ensure required columns exist
  stopifnot(all(c("spat.unit", "year", "age_idx", "length_mm") %in% names(lmu_df)))
  stopifnot(all(c("spat.unit", "shfa", "rafa", "mufb", "sdfb") %in% names(fec_dpars)))
  
  nsu <- nrow(fec_dpars)
  
  message("Simulating fecundity using uncertainty in a and b parameters...")
  
  # Preallocate output list
  out_list <- vector("list", nsu)
  
  for (s in seq_len(nsu)) {
    su_name <- fec_dpars$spat.unit[s]
    
    # Draw random samples for a and b
    fa_draws <- rgamma(ndraws, shape = fec_dpars$shfa[s], rate = fec_dpars$rafa[s])
    fb_draws <- rnorm(ndraws, mean = fec_dpars$mufb[s], sd = fec_dpars$sdfb[s])
    
    # Subset the deterministic lengths for this spatial unit
    lsu <- lmu_df %>% filter(spat.unit == su_name)
    
    # Calculate predicted fecundity for each sample
    fmu_samples <- replicate(
      ndraws,
      lsu$length_mm^sample(fb_draws, 1) * sample(fa_draws, 1)
    )
    
    # Summarize posterior predictive distribution per row (age × year)
    lsu_summary <- lsu %>%
      mutate(
        fmu_med = apply(fmu_samples, 1, median, na.rm = TRUE),
        fmu_low = apply(fmu_samples, 1, quantile, probs = 0.025, na.rm = TRUE),
        fmu_high = apply(fmu_samples, 1, quantile, probs = 0.975, na.rm = TRUE)
      )
    
    out_list[[s]] <- lsu_summary
  }
  
  result <- bind_rows(out_list)
  
  message("✅ Finished computing f.mu summaries across spatial units.")
  return(result)
}

#fec_samples_df <- do.call(rbind, fec.samples$samples) |> as.data.frame()

#lmu_df <- lmu_df %>% left_join(data.biph %>% distinct(su,spat.unit)) %>% select(-su)
fmu_summary <- compute_fmu_summary_from_lmu_df(
  lmu_df = lmu_df %>% left_join(data.biph %>% distinct(su,spat.unit)),
  fec_dpars = fec.dpars,
  ndraws = 2000
)
lmu_fec <- lmu_df %>%
  left_join(fmu_summary %>% select(spat.unit, su, year, age_idx, fmu_med, fmu_low, fmu_high),
            by = c("spat.unit", "year", "age_idx"))

saveRDS(lmu_fec, file = paste0(home,"/data/lmu_fec_1104.RData"))
```

### Reshape l.mu and f.mu:s
```{r}
# but first save lmu and fmu.
#flmu_list <- list(fmu_list,lmu_list)
#saveRDS(flmu_list, file = paste0(home,"/data/flmu_list_1102.RData"))


flmu_chunk <- function(flmu_list_chunk) {
  purrr::imap_dfr(flmu_list_chunk, function(mat, draw_id) {
    tibble::tibble(
      draw = as.integer(draw_id),
      age  = rep(seq_len(nrow(mat)), times = ncol(mat)),
      ind  = rep(seq_len(ncol(mat)), each = nrow(mat)),
      value = as.vector(mat)
    )
  }) |>
    dplyr::filter(!is.na(value)) |>
    dplyr::group_by(age, ind) |>
    dplyr::summarise(
      q50 = median(value),
      q025 = quantile(value, 0.025),
      q975 = quantile(value, 0.975),
      .groups = "drop"
    )
}

flmu_mqi <- function(flmu_list, chunk_size = 250) {
  n_draws <- length(flmu_list)
  chunks <- split(seq_len(n_draws), ceiling(seq_len(n_draws) / chunk_size))
  
  chunk_summaries <- purrr::map(chunks, function(idx) {
    summarise_lmu_chunk(flmu_list[idx])
  })
  
  # Combine across chunks by taking median of medians, etc.
  dplyr::bind_rows(chunk_summaries) |>
    dplyr::group_by(age, ind) |>
    dplyr::summarise(
      median = median(q50, na.rm = TRUE),
      lower  = median(q025, na.rm = TRUE),
      upper  = median(q975, na.rm = TRUE),
      .groups = "drop"
    )
}

lmu_df <- flmu_mqi(flmu_list)

#f.mu samps
fmu_df <- flmu_mqi(fmu_list)

flmu_df <- bind_rows(lmu_df %>% mutate(variable = "l.mu"), lmu_df %>% mutate(variable = "f.mu"))
saveRDS(flmu_df, file = paste0(home,"/data/flmu_df_1102.RData"))

```

approach 1, unfinished but using growth parameters estimates to predict l.mu
```{r}
growth.samples <- biph.samples[1:2000,]

growth_pars1 <- growth.samples %>%
  spread_draws(log_p.year[yr,sup], sep = ",") %>%
  filter(sup %in% 1:12) %>% # first 12 sup:s are Linf 
  rename(Linf = log_p.year,
         su = sup) %>%
  ungroup() %>%
  #filter(.chain == 1) %>%
  select(-.iteration,-.chain)

growth_pars2 <- growth.samples %>%
  spread_draws(log_p.year[yr,sup], sep = ",") %>%
  filter(sup %in% 13:24) %>% 
  mutate(su = sup - 12) %>% 
  rename(k = log_p.year) %>%
  ungroup() %>%
  #filter(.chain == 1) %>%
  select(-.iteration,-.chain,-sup)

growth_pars3 <- growth.samples %>%
  spread_draws(lb.mu[su], g[yr,su], sep = ",") %>%
  ungroup() %>%
  #filter(.chain == 1) %>%
  select(-.iteration,-.chain)

#su:s in growth data
sun <- data.biph %>% distinct(su, spat.unit)
growth.pars <- left_join(growth_pars1, growth_pars2) %>%
  left_join(growth_pars3) %>%
  left_join(sun) %>%
  select(-su)

# smolt age samples
sages <- growth.samples %>%
  spread_draws(smo.age[i]) %>%
  ungroup() %>%
  #filter(.chain == 1) %>%
  select(-.iteration,-.chain)

#fec
samplesf <- fec.samp$samples$chain1[1:2000,]
sunf <- data.fec %>%
  distinct(spat.unit,su)

fec_pars <- samplesf %>%
  spread_draws(a[su], b[su],sep = ",") %>%
  select(-.iteration,-.chain) %>%
  ungroup() %>%
  left_join(sunf) %>%
  select(-su)

# Step 3: join the two draw frames (assuming independence)
# This matches draw i from each posterior; you can also do cartesian join if needed
# joint_draws <- bind_cols(
#   growth_pars %>% arrange(.draw),
#   fec_pars %>% arrange(.draw) %>% select(-.draw)
# )

joint_draws <- 
  growth.pars %>% 
  filter(spat.unit %in% sunf$spat.unit) %>%
  left_join(fec_pars %>% filter(spat.unit %in% sun$spat.unit),
            by = join_by(.draw,spat.unit))
  
joint_draws_age <- joint_draws %>%
  expand_grid(age = 1:10)
  
# Step 4: Generate predicted length and fecundity per draw
# Replace with your actual function that rebuilds length for given parameters
length_pred <- function(lb_mu, par, g, age, doy_dec = 1) {
  # Example placeholder: VB increment
  lb_mu + (exp(Linf) - lb_mu) * (1 - exp(-exp(k) * age * doy_dec))
}

fec_pred <- function(L, a, b) a * L^b

# Suppose you want predictions for su = 1..nsu, years = vector of interest
preds <- 
  expand_grid(su = 1:nsu,
              year = years_vec,
              draw = 1:nrow(joint_draws)) %>%
  # extract parameters per draw/spatial unit
  mutate(lb = map2_dbl(draw, su, ~ joint_draws[[paste0("lb.mu[", .y, "]")]][.x]),
         a  = map2_dbl(draw, su, ~ joint_draws[[paste0("a[", .y, "]")]][.x]),
         b  = map2_dbl(draw, su, ~ joint_draws[[paste0("b[", .y, "]")]][.x]),
         # for brevity, pick one age for fecundity (say age=2)
         L  = predict_length(lb, 
                             par = c(joint_draws[[paste0("log_p.year[", year, ",", su, "]")]][draw]),
                             g   = joint_draws[[paste0("g[", year, ",", su, "]")]][draw],
                             age = 2),
         fec = predict_fecundity(L, a, b))

# Step 5: summarize with tidybayes
fec_summary <- preds %>%
  group_by(su, year) %>%
  median_qi(fec, .width = c(.5, .8, .95))

fec_summary
```
