---
title: "Salmon Biphasic growth and fecundity model outputs"
author: "Viktor Thunell" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    page-layout: full
    embed-resources: true
    toc: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 80%
editor: source
execute: 
  echo: true
  eval: true
  cache: true
---

## Load libraries

```{r}
#| message: false
#| warning: false
#| cache: false

# Load libraries, install if needed
pkgs <- c("tidyverse", "tidylog", "devtools","viridis","nls.multstart", "broom", "patchwork", "posterior", "boot", "tidybayes","bayesplot", "nimbleHMC", "here", "purrr")

# remotes::install_github("nimble-dev/nimble", ref = "devel", subdir = "packages/nimble")

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){
    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  }

invisible(lapply(pkgs, library, character.only = T))

options(ggplot2.continuous.colour = "viridis")
theme_set(theme_minimal())

# Set path
color_scheme_set("viridis")
home <- here::here()
```

## Length at age 

### Read and define data

```{r}
#| message: false
#| warning: false
#| cache: false

#sallaa <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-laa_2026-01-30.RData")) %>%
sallaa <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-laa_2026-03-31.RData")) %>%
  drop_na(length_mm) %>%
  rename(year = fi_year,
         site = sai_location,
         sea.age = sea_age_year,
         juv.age = juvenile_age_year,
         tot.age = tot_age_year,
         lat = fisa_y_4326,
         lon = fisa_x_4326) %>%
  #filter out tot.age = 0 individuals
  filter(!(sea.age == 0 & juv.age == 0)) %>%
  #filter out non-aged individuals (~90000 individuals)
  filter(!(is.na(sea.age) & is.na(juv.age))) %>%
  # removes smolt.age = 0
  filter(!(age.type == "both" & juv.age == 0)) %>%
  mutate(hatch.year = year-tot.age) %>% # to filter data based o hatch year instead of year to predict growth pars before catch year
  filter(!is.na(juv.age), # removes age.type = "sea.only"
         !is.na(year),
         #hatch.year > 2000
         #hatch.year > 2006
         ) 

set.seed(1)
data.biph_m <- sallaa %>%
  filter(hatch.year > 2000,
         age.type == "both",
         #sea.age > 0
         ) #%>%
  #slice_sample(n = 50000)

data.biph <- sallaa %>%
  filter(age.type == "juve.only") %>% 
  bind_rows(data.biph_m) %>%
  mutate(yday.may1 = if_else(is.na(date), 1, yday(date) - yday("2025-05-01")+1), 
         doy.dec = if_else(yday.may1 > 0, yday.may1, yday.may1+365)/365,
         tot.age.dec = if_else(yday.may1 > 0, tot.age+doy.dec, tot.age+doy.dec-1),
         smo_age = if_else(age.type == "both" | is_smo == 1, juv.age, NA),
         sea.age = if_else(is.na(sea.age), 0, sea.age),
         growth.year = trunc(tot.age.dec)+1, # + 1 to index age 0 individuals
         hatch.year = year-tot.age,
         hatch.year.f = as.numeric(factor(hatch.year, levels = sort(unique(hatch.year)), labels = seq_along(sort(unique(hatch.year))))),
         year.f = as.integer(factor(year)),
         sex = as.integer(factor(sex)),
         su = as.integer(factor(spat.unit)),
         basin = if_else(str_detect(spat.unit, "AU"),"BS","NA"),
         bs = as.integer(factor(basin))) %>%
  mutate(ind.id = row_number()) 
```

### Plot length at age data
```{r}
data.biph %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot(aes(tot.age, length_mm, color = factor(sex)), alpha = 0.3) +
  geom_point(size = 0.1) +
  facet_grid(age.type~sex) +
  scale_x_continuous(breaks = seq(0, 13, 1) ) +
  theme_minimal()  

data.biph %>%
  ggplot() +
  geom_density(aes(x = tot.age, color = basin, fill = sex), alpha = 0.3) +
  xlim(0, 13) +

data.biph %>% 
  ggplot() + 
  geom_density(aes(x = length_mm, color = basin, fill = sex), alpha = 0.3)

data.biph %>% 
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot() +
  geom_density(aes(x = length_mm, fill = factor(sex)), alpha = 0.5) +
  facet_wrap(~tot.age, scales = "free_y") +
  labs(caption = "length density by age") 

# age at smoltification by spatial unit
data.biph %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  filter(age.type == "both") %>%
  ggplot() +
  geom_density(aes(x = juv.age, fill = factor(sex)),  alpha = 0.3) +
  facet_wrap(~spat.unit) +
  labs(x = "age at smoltification") 
  #xlim(-1, 5)

# juvenile size at age
data.biph %>%
  filter(age.type == "juve.only",
         #spat.unit == "Upper-Normandy"
         ) %>%
  ggplot(aes(x = juv.age, y =length_mm)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 3)) +
  #geom_smooth(method = lm) +
  facet_wrap(~spat.unit)
  
data.biph %>%
  filter(!age.type == "sea.only",
         #spat.unit == "Brittany"
         ) %>%
  ggplot(aes(x = tot.age, y =length_mm, color = age.type)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 3)) +
  scale_x_continuous(breaks = seq(0, 13, 1), limit = c(0,NA) ) +
  #geom_smooth(method = lm) +
  facet_wrap(~spat.unit)

data.biph %>%
  #filter(age.type == "both") %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot(aes(tot.age, length_mm, color = factor(smo_age))) +
  geom_point(alpha = 0.3, size = 0.5) +
  facet_wrap(~spat.unit) +
  scale_x_continuous(breaks = seq(0, 13, 1), limit = c(0,NA) ) +
  theme_minimal()
```

## NLS for vbgf params
```{r}
fit_vbgf <- function(df) {
  nls_multstart(length_mm ~ Linf*(1-exp(-k*age)), 
              iter = 1500,
              data = df, 
              start_lower = c(Linf = 100, k = 0.1), 
              start_upper = c(Linf = 300, k = 0.9))
}

vbgf_fits <- data.biph %>%
  filter(age.type == "juve.only",
         !spat.unit %in% c("Baltic-sea-AU1") # this wont converge
         ) %>%
  select(spat.unit,juv.age,length_mm) %>%
  rename(age = juv.age) %>% 
  group_by(spat.unit) %>% 
  nest() %>% 
  mutate(model = map(data, fit_vbgf))

vbgf_fits %>%
  mutate(ests = map(model, broom::tidy,  conf.int = TRUE)) %>%
  unnest(ests) %>%
  pivot_wider(id_cols = c(spat.unit), names_from = term, values_from = c(estimate, conf.low, conf.high)) %>%
  ggplot(aes(estimate_k, estimate_Linf, color = spat.unit, label = spat.unit)) +
  geom_point() +
  geom_text(vjust = 0, nudge_y = 2, show.legend = FALSE, color = "black") +
  #coord_cartesian(expand = 2) +
  geom_errorbar(aes(ymin = conf.low_Linf, ymax = conf.high_Linf)) +
  geom_errorbar(aes(xmin = conf.low_k, xmax = conf.high_k)) +
  labs(title = "freshwater VBGF params")

vbgf_fits <- data.biph %>%
  filter(age.type == "both") %>%
  rename(age = sea.age) %>%
  select(spat.unit,age,length_mm) %>%
  group_by(spat.unit) %>% 
  nest() %>% 
  mutate(model = map(data, fit_vbgf))

# Estimates by river and sex
vbgf_fits %>%
  mutate(ests = map(model, broom::tidy,  conf.int = TRUE)) %>%
  unnest(ests) %>%
  pivot_wider(id_cols = c(spat.unit), names_from = term, values_from = c(estimate, conf.low, conf.high)) %>%
  ggplot(aes(estimate_k, estimate_Linf, color = spat.unit, label = spat.unit)) +
  geom_point() +
  geom_text(vjust = 0, nudge_y = 2, show.legend = FALSE, color = "black") +
  #coord_cartesian(expand = 2) +
  geom_errorbar(aes(ymin = conf.low_Linf, ymax = conf.high_Linf)) +
  geom_errorbar(aes(xmin = conf.low_k, xmax = conf.high_k)) +
  labs(title = "marine VBGF params")
```

### Source models / Load samples
```{r}
laa.samplesWAIC <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/biph1_0_samples_2026-03-18.RData")
laa.samplesWAIC <- readRDS("/Users/vitl0001/gitProjects/diasp-lht/data/biph1_0_4_samples_2026-05-04.RData")

# biph1_0.samples$WAIC # 312954.1 10/3
# biph1_0.samples_test$WAIC # 312911.5 10/3
#laa.samples$WAIC # 312954.1 10/3
#laa.samples$WAIC # 675015.2 2/4
laa.samplesWAIC$WAIC # 667375.3 14/4 , 676518.5 18/4

laa.samples <- laa.samplesWAIC$samples %>%
  as_draws()


laa.samples <- biph1_0_4.samples$samples %>%
  as_draws()
# # Or source model code and mcmc (load libs and data)
# t <- Sys.time()
# source(file = paste0(home,"/R/model devel/2-2_model_salmon_biphasic_v6.R"))
# Sys.time() - t # approx 12 hours with 12 000 NUTS mcmc samples

# laa.samples %>%
#   spread_draws(par_f[su,par], par_m[su,par], sep = ",") %>%
#   filter(par == 2) %>%
#   # mutate(par_f = exp(par_f),
#   #        par_m = exp(par_m)) %>%
#   ggplot(aes(par_f, par_m, color = su, group = su)) +
#   geom_point() +
#   geom_smooth(method = lm)
```

### Traces, rhats and ees

```{r}
node.sub <- subset_draws(as_draws(laa.samples), variable = "sig_l")
node.sub %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail"))

# node.sub <- subset_draws(as_draws(laa.samples), variable = c("l_mean_m_bs", "k_mean_m_bs"))
# node.sub %>% mcmc_trace()
# node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail"))

# su 1, 14 and 8 are odd (Adour, upper Normandy and Brittany)
#data.biph %>% distinct(spat.unit,su)
node.sub <- subset_draws(as_draws(laa.samples), variable = "par_f")
node.sub %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>%
  #arrange(-rhat) %>% 
  mutate(mean_n = exp(mean))

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_m")
#node.sub[,sample(1:ncol(node.sub), 36)] %>% mcmc_trace()
node.sub[] %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>% mutate(mean_n = exp(mean)) %>% arrange(-rhat)

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_sig_f")
node.sub %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>% mutate(mean_n = exp(mean))

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_sig_m")
node.sub %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>% mutate(mean_n = exp(mean)) %>% arrange(-rhat)

# su 14 and 8 are odd
node.sub <- subset_draws(as_draws(laa.samples), variable = "lh_mu")
node.sub %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>% mutate(mean_n = exp(mean)) 

node.sub <- subset_draws(as_draws(laa.samples), variable = "R")
node.sub[,sample(1:ncol(node.sub), 36)] %>% mcmc_trace()
node.sub %>% summarise_draws(c("mean","median","sd","rhat","ess_bulk","ess_tail")) %>% mutate(mean_n = exp(mean)) %>% arrange(-rhat)

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_m")
node.sub2 <- subset_draws(as_draws(laa.samples), variable = "par_sig_m")
plot(node.sub2[,1],node.sub2[,1])

```
# Density of pars
```{r}
# node.sub <- subset_draws(as_draws(laa.samples), variable = c("l_mean_m_bs", "k_mean_m_bs"))
# node.sub %>%
#   gather_draws(l_mean_m_bs[bs], k_mean_m_bs[bs]) %>%
#   left_join(data.biph %>% distinct(bs, basin)) %>%
#   ggplot() +
#   geom_density(aes(.value, color = factor(basin))) +
#   facet_wrap(~.variable, scales = "free_x")

node.sub <- subset_draws(as_draws(laa.samples), variable = c("lh_mu"))
node.sub %>%
  gather_draws(lh_mu[su]) %>%
  #median_qi()
  left_join(data.biph %>% distinct(su, spat.unit)) %>%
  ggplot() +
  geom_density(aes(.value, color = factor(spat.unit))) 

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_f")
node.sub %>%
  spread_draws(par_f[su,par], sep = ",") %>%
  # median_qi() %>% arrange(par) %>%
  left_join(data.biph %>% distinct(su, spat.unit)) %>%
  # mutate(par_f = exp(par_f)) #%>%
  filter(par == 1,
         #spat.unit == "Brittany"
         ) %>%
  ggplot() +
  geom_density(aes(par_f, color = factor(spat.unit))) 
  #facet_wrap(~factor(spat.unit), scales = "free") 

node.sub %>%
  spread_draws(par_f[su,par], sep = ",") %>%
  left_join(data.biph %>% distinct(su, spat.unit)) %>%
  mutate(par_f = par_f) %>%
  filter(par == 2,
         #spat.unit == "Brittany"
         ) %>%
  ggplot() +
  geom_density(aes(par_f, color = factor(spat.unit)))  
  #facet_wrap(~factor(su), scales = "free")

node.sub <- subset_draws(as_draws(laa.samples), variable = "par_m")
# spatial model 
node.sub %>%
  spread_draws(par_m[su,par], sep = ",") %>%
  #median_qi() %>% 
  #arrange(par) %>%
  #mutate(par_m = exp(par_m)) %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  filter(par == 1) %>%
  ggplot() +
  geom_density(aes(exp(par_m), color = factor(spat.unit))) 

node.sub %>%
  spread_draws(par_m[su,par], sep = ",") %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  filter(par == 2) %>%
  ggplot() +
  geom_density(aes(exp(par_m), color = factor(spat.unit))) 


node.sub <- subset_draws(as_draws(laa.samples), variable = c("smo_age"))
node.sub[,sample(1:50000,10000)] %>%
  gather_draws(smo_age[i]) %>%
  left_join(data.biph %>% mutate(i = row_number()) %>% select(i, spat.unit)) %>%
  ggplot() +
  geom_density(aes(.value, color = spat.unit)) +
  facet_wrap(~spat.unit, scales = "free_x")

```

### Predicted / observed

```{r}

keeps <- which(!is.na(laa.samples[1, ]))
laa.samples_tmp <- laa.samples[, keeps]

laa.samples_tmp2 <- laa.samples %>%
  spread_draws(l_mu[gy,i], sep = ",") %>%
  median_qi()

dfl_old <- data.biph %>%
  select(length_mm,spat.unit, smo_age, tot.age, age.type, ind.id) %>%
  rename(obs_l = length_mm) %>%
  #mutate(ind.id = row_number()) %>%
  #slice_sample(n = 40000) %>%
  left_join(laa.samples %>%
              rename(pred.l = l_mu,
                     ind.id = i) %>%
              ungroup(), join_by(ind.id))

dfl_old %>%
  #filter(age.type == "juve.only") %>%
  #filter(age.type == "both") %>%
  filter(trunc(tot.age) == gy-1) %>% 
  ungroup() %>%
  ggplot() +
  geom_abline(slope = 1) +
  geom_point(aes(x = obs_l, y = pred.l, color = age.type), shape = 4,alpha = 0.5) +
  theme_minimal() +
  facet_wrap(~spat.unit)

```

### Predicted curves

```{r}
tmp <- laa.samples %>%
  spread_draws(par_f[su,par], par_m[su,par], lh_mu[su], sep = ",") %>%
  #spread_draws(par_f[su,par], sep = ",") %>%
  median_qi()
  
tmpb <- tmp %>%
  select(su, par, lh_mu,par_f,par_m) %>%
  pivot_wider(id_cols = c(su,lh_mu), names_from = par, values_from = c(par_f,par_m)) %>%
  expand_grid(age = 0:10,smo_age = 1:5) %>% arrange(smo_age) %>%
  mutate(length = NA,
         j=age+1,
         doy.dec = runif(1,0,1),
         par_m_3 = exp(par_m_1)/exp(par_m_2),
         par_f_3 = exp(par_f_1)/exp(par_f_2)) %>%
  left_join(data.biph %>% distinct(su,spat.unit))

#step(smo_age[i] - (gy-0.999) evaluates to 1 when smo_age > gy - .99
# Smolt run is in april-may so ending that year of growth with smoltification. if smotl age == 2, growth year three should be in the marine habitat. So when growth year (j) <= smolt age, they grow in freshwater and when j > smolt age, marine habitat it is

nage = length(unique(tmpb$age))
nsa = length(unique(tmpb$smo_age))
for(i in 1:nrow(tmpb)){
  if(i %% nage == 1) {
  tmpb$length[i] <- biph_step(
    l_prev  = tmpb$lh_mu[i],
    L_f     = tmpb$par_f_3[i],#exp(tmpb$par_f_1[i]),
    L_m     = tmpb$par_m_3[i],   
    k_f     = exp(tmpb$par_f_2[i]),
    k_m     = exp(tmpb$par_m_2[i]),
    doy_dec = 1,#tmpb$doy.dec[i],
    j       = 1,
    age     = tmpb$age[i],
    smo_age = tmpb$smo_age[i])
  } else {
  tmpb$length[i] <- biph_step(
    l_prev  = tmpb$length[i-1],
    L_f     = tmpb$par_f_3[i],   #exp(tmpb$par_f_1[i]),
    L_m     = tmpb$par_m_3[i],   
    k_f     = exp(tmpb$par_f_2[i]),
    k_m     = exp(tmpb$par_m_2[i]),
    doy_dec = 1,#tmpb$doy.dec[i],
    j       = tmpb$j[i],
    age     = tmpb$age[i],
    smo_age = tmpb$smo_age[i]) 
  }
  }

data.biph %>% distinct(spat.unit)
tmpb %>%
  #filter(spat.unit == "Baltic-sea-AU1") %>%
  ggplot() +
  geom_line(aes(x=j, y=length, color = factor(smo_age)), alpha = 0.5) +
  geom_point(data = data.biph, aes(tot.age, length_mm, color = factor(smo_age)), alpha = 0.3, size = 0.8) +
  #geom_point(data = data.biph %>% filter(spat.unit == "Baltic-sea-AU1"), aes(tot.age, length_mm, color = factor(smo_age)), alpha = 0.3, size = 0.8) +
  facet_wrap(~spat.unit, scales = "free") +
  scale_x_continuous(breaks = seq(0, 10, 1) ) 

tmpb %>%
  filter(age < smo_age) %>%
  ggplot() +
  geom_line(aes(x=j, y=length, color = factor(smo_age)), alpha = 0.5) +
  geom_point(data = data.biph %>% filter(age.type == "juve.only") , aes(tot.age, length_mm, color = factor(smo_age)), alpha = 0.3, size = 0.8) +
  #geom_point(data = data.biph %>% filter(spat.unit == "Baltic-sea-AU1"), aes(tot.age, length_mm, color = factor(smo_age)), alpha = 0.3, size = 0.8) +
  facet_wrap(~spat.unit, scales = "free") +
  scale_x_continuous(breaks = seq(0, 10, 1) ) 

```


```{r}
pf<- tmp %>%
  pivot_wider(id_cols = su, names_from = "par", values_from = "par_f") %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  rename(linf = "1",
         k = "2") %>%
  mutate(linf = round(exp(linf),1),
         k = round(exp(k),6)) %>%
  expand_grid(gy = 0:4) %>%
  mutate(length = linf*(1 - exp(-k*gy))) %>%
  ggplot() +
  geom_line(aes(x=gy, y  = length)) +
  geom_point(data = data.biph %>% filter(age.type == "juve.only"), aes(tot.age+1, length_mm, color = factor(su)), alpha = 0.1) +
  facet_wrap(~spat.unit)

tmp_m <- laa.samples %>%
  spread_draws(par_m[su,par], sep = ",") %>%
  median_qi() 
  
pm <-tmp_m %>% 
  # mutate(su = if_else(par < 14, par, par-13),
  #        par = if_else(par < 14, 1, 2)) %>%
  pivot_wider(id_cols = su, names_from = "par", values_from = "par_m") %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  rename(linf = "1",
           k = "2") %>%
  mutate(linf = exp(linf),
         k = exp(k)) %>%
  #expand_grid(age = 2:8, cohort = seq(1,25, by=5)+1997) %>%
  expand_grid(gy = 2:8) %>%
  #mutate(length = , .by = cohort ) %>%
  mutate(length = linf*(1 - exp(-k*gy))) %>%
  ggplot() +
  geom_line(aes(x=gy, y=length)) +
  geom_point(data = data.biph %>% filter(age.type == "both"), aes(tot.age+1, length_mm, color = factor(su)), alpha = 0.1) +
  facet_wrap(~spat.unit)
    
         
pf + pm

```


### length at age variables

```{r}
laa.samples %>%
  gather_draws(linf[su,sex], sep = ",") %>%
  ungroup() %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot() +
  geom_density(aes(x = exp(.value), color = factor(sex))) +
  facet_wrap(~spat.unit, scales = "free", ncol = 3) +
  theme_minimal() +
  labs(x = "Linf")

laa.samples %>%
  gather_draws(g[su]) %>%
  ungroup() %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  ggplot() +
  geom_density(aes(x = exp(.value), color = spat.unit)) +
  theme_minimal() +
  labs(x = "g (juvenile growth rate")

laa.samples %>%
  gather_draws(sig.l,sig.lj) %>%
  ggplot() +
  geom_density(aes(x = .value, color = .variable)) +
  facet_wrap(~.variable, scales = "free", ncol = 3) +
  theme_minimal() 

laa.samples %>%
  gather_draws(k.year[su,sex,year], sep = ",") %>%
  ungroup() %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot() +
  geom_boxplot(aes(x = exp(.value), y = spat.unit, color = factor(sex)),
               outliers = FALSE) +
  theme_minimal() +
  #xlim(0,)+
  coord_cartesian(xlim = c(-0.5,4)) +
  labs(y = "", x = "k")

laa.samples %>%
  gather_draws(linf[su,sex], sep = ",") %>%
  ungroup() %>%
  left_join(data.biph %>% distinct(su,spat.unit)) %>%
  mutate(sex = ifelse(sex == 1, "m","f")) %>%
  ggplot() +
  geom_boxplot(aes(x = exp(.value), y = spat.unit, color = factor(sex)),
               outliers = FALSE) +
  theme_minimal() +
  labs(y = "", x = "linf")

```

### k over time
```{r}
tmpP <- laa.samples %>%
  gather_draws(par_m[year, supar], sep = ",") 

tmpP <- tmpP %>%
  ungroup() %>%
  mutate(su = if_else(supar > 14, supar - 14, supar),
         par = if_else(supar > 14, "k", "linf")) %>%
  left_join(data.biph %>% distinct(su, spat.unit)) %>% 
  mutate(year = year + 2006) 

tmpP %>%
  filter(year > 2010) %>%
  ungroup() %>%
  filter(par == "k") %>%
  ggplot() +
  geom_boxplot(aes(x = year, y = exp(.value), group = year), color = "#00BFC4", outliers = FALSE) +
#  geom_line(aes(y = exp(m_length), x = year), color = "#00BFC4", alpha = 0.4) +
  facet_wrap(~spat.unit, scales = "free") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1, size = rel(.75))) 
  ylim(0,2)
  tmpP %>%
  filter(year > 2010) %>%
  ungroup() %>%
  filter(par == "linf") %>%
  ggplot() +
  geom_boxplot(aes(x = year, y = exp(.value), group = year), color = "#00BFC4", outliers = FALSE) +
#  geom_line(aes(y = exp(m_length), x = year), color = "#00BFC4", alpha = 0.4) +
  facet_wrap(~spat.unit, scales = "free") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1, size = rel(.75))) +
    ylim(0,3000)

```

### Correlation/covariance matrix
```{r}
# median sample correlation 
samp <- laa.samples

cols <- grep("^R",colnames(as.matrix(samp)))
ner = length(unique(data.biph$spat.unit))
samp[,cols][,784]
corr_arr <- array(NA, dim = c(ner*2, ner*2, nrow(samp)))

for (i in 1:nrow(samp)) {

  R_sample <- matrix(
    as.numeric(samp[i, cols]),
    nrow = ner*2,
    ncol = ner*2,
    byrow = FALSE
  )

  corr_arr[, , i] <- crossprod(R_sample)
}

corr <- apply(corr_arr, c(1, 2), median)

var.lats <- data.biph %>%
  mutate(m.lat = mean(fisa_y_4326.x), .by = spat.unit) %>%
  distinct(su, spat.unit, m.lat) %>%
  arrange(-m.lat)

data.biph %>%
  filter(is.na(fisa_y_4326.x))
  mutate(m.lat = mean(lat), .by = spat.unit) %>%
  distinct(su, spat.unit, m.lat) %>%
  

su.labs <- var.lats %>%
  select(su, spat.unit) %>%
  bind_rows(var.lats %>%
  select(su, spat.unit) %>% mutate(su = su+ner)) %>%
  { setNames(.$spat.unit, .$su) } 
  
  
as.data.frame(corr) %>%
  mutate(r = row_number()) %>%
  pivot_longer(cols = -r, names_to = "c", values_to = "value") %>%
  mutate(c = as.integer(gsub("V", "", c)) ) %>%
  left_join(var.lats, by = c("r" = "su")) %>%
  left_join(var.lats, by = c("c" = "su"), suffix = c(".x", ".y")) %>%
  mutate(r = reorder(r, m.lat.x),
         c = reorder(c, -m.lat.y)) %>%
  ggplot(aes(x=c, y=r, fill = value)) + 
  geom_tile() +
  scale_fill_viridis_c() +
  scale_x_discrete(labels = su.labs) +
  scale_y_discrete(labels = su.labs) +
  theme(axis.text = element_text(angle = 45, hjust = 1, size = rel(.75)))


as.data.frame(corr) %>%
  mutate(r = row_number()) %>%
  pivot_longer(cols = -r, names_to = "c", values_to = "value") %>%
  mutate(c = as.integer(gsub("V", "", c)) ) %>%
  # left_join(var.lats, by = c("r" = "su")) %>%
  # left_join(var.lats, by = c("c" = "su"), suffix = c(".x", ".y")) %>%
  # mutate(r = reorder(r, m.lat.x),
  #        c = reorder(c, -m.lat.y)) %>%
  ggplot(aes(x=c, y=r, fill = value)) + 
  geom_tile() +
  scale_fill_viridis_c() +
  scale_x_discrete(labels = su.labs) +
  scale_y_discrete(labels = su.labs) +
  theme(axis.text = element_text(angle = 45, hjust = 1, size = rel(.75)))
```
