---
title: "Combine salmon and habitat data DIASPARA 2.2"
author: "Viktor Thunell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    code-fold: true
    code-summary: "Show code"
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 80%
editor: source
execute: 
  echo: true
  eval: true
  cache: false
---

## Load libraries

```{r libs}
#| message: true
#| warning: false

# Load libraries, install if needed
pkgs <- c("tidyverse","tidylog","viridis","arrow","sf")

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){
  
    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  
  }

invisible(lapply(pkgs, library, character.only = T))

options(ggplot2.continuous.colour = "viridis")
#theme_set(theme_grey()) # check why global theme option not working when rendering
devtools::source_url("https://raw.githubusercontent.com/VThunell/diasp-lht/main/R/functions/map-plot.R") # message of SHA-1 hash for file

# Set path
home <- here::here()

```
## Read data

```{r}
# #| message: false
# #| warning: false
# #| cache: false
# 
# sallaa <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-laa_2026-03-09.RData")) %>%
#   rename(year = fi_year,
#          site = sai_location,
#          sea.age = sea_age_year,
#          juv.age = juvenile_age_year,
#          tot.age = tot_age_year,
#          lat = fisa_y_4326,
#          lon = fisa_x_4326) %>%
#   #filter out non-aged individuals (~90000 individuals)
#   filter(!(is.na(sea.age) & is.na(juv.age))) %>%
#   filter(!is.na(juv.age),
#          !is.na(year),
#          year > 2000)
# 
# df <- sallaa %>%
#   slice_sample(n = 100)
```

```{r}
# rs <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/riversegments/", format = "parquet")

ca <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/catchments/", format = "parquet")

# schema(ca)
# 
# ca %>%
#   select(shape) %>%
#   collect()
```


# plot catchm. shapes
```{r}
ca_sf <- ca %>%
  #slice_head(n = 10000) %>%
  collect() %>%
  mutate(geometry = st_as_sfc(shape, EWKB = TRUE, crs = 4326)) %>%
  st_as_sf(sf_column_name = "geometry")

# ca_sf %>%
#   ggplot() +
#   geom_sf()
```
# plot riverseg. shapes
```{r}
# rs_sf <- rs %>%
#   #slice_head(n = 10000) %>%
#   collect() %>%
#   mutate(geometry = st_as_sfc(geom, EWKB = TRUE, crs = 4326)) %>%
#   st_as_sf(sf_column_name = "geometry")
# 
# rs_sf %>%
#   ggplot() +
#   geom_sf()
```
# open wgnas refs
```{r}
rn <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/refnas/refnas_tr_area_are_polygon.parquet", format = "parquet")

rn_df <- rn %>% collect()

# NULL list elements in the polygons
rn_df %>%
  filter(map_lgl(geom_polygon, is.null))

rn_sf <- rn_df %>% 
  filter(!map_lgl(geom_polygon, is.null)) %>%
  mutate(geom = st_as_sfc(geom_polygon, EWKB = TRUE, crs = 4326)) %>%
  st_as_sf(sf_column_name = "geom")

rn_sf %>%
  #filter(are_lev_code == "River") %>%
  distinct(are_lev_code)

plot_map_Euro +
  geom_sf(data = rn_sf %>% filter(
              are_lev_code %in% c("Assessment_unit")), aes(fill=are_lev_code), alpha = 0.5)
```

```{r}
library(DBI)
library(RPostgres)
library(dplyr)

con <- DBI::dbConnect(drv=RPostgres::Postgres(),
		dbname = "diaspara",
		host = "185.135.126.250",
		user = "diaspara_read",
		password = "diaspara_read_*123"  
)

area <- dbGetQuery(con, "SELECT 
				are_id,
				are_are_id, 
				are_code,
				are_lev_code,
				are_ismarine,
				are_rivername FROM refbast.tr_area_are;")

save(area, file = "C:/workspace/DIASPARA_WP3_habitat/data/area.Rdata")

get_area <- function(are_id, area, tab=data.frame()) {
	if (is.na(are_id)) {
		return(tab) 
	} else {
		if (nrow(tab)==0){
			tab <- area[area$are_id == are_id,]
		} else {			
			tab <- rbind(tab, area[area$are_id == are_id,])
		}
		are_id <- tab[nrow(tab), "are_are_id"]
		get_area(are_id, area, tab)		
	}
}


# So we can use a recursive from R 
hierar <- get_area(area,are_id = 1275)

# or from postgres

get_area_postgres <- function( con, are_id){
	return(dbGetQuery(con, "SELECT * FROM ref.get_parent_area(1275, 'WGBAST')"))
}

hierar <- get_area_postgres(con, are_id = 1275)
# Lets say you have the main_river code as a vector from your points (you know this by spatial join between points and the river segment)

main_rivers <- c("20056363", "20056030")

selected_areas <- dplyr::left_join(data.frame("main_riv"= main_rivers), area, by = join_by("main_riv" == "are_code"))

# to work with more than one argument to the function I would use mapply

ll <- mapply(get_area, selected_areas$are_id, MoreArgs = list(area=area),SIMPLIFY = FALSE)
bind_rows(ll)
```



# Cedrics join input
```{r}
# st_join(points, rivers, join = st_nearest_feature, left = T) 
# And then you get all variables from rivers.
# Would that work?
# The best is to create a table joining all observation id and river segment id. And use it later in your code.
df.sf <- st_as_sf(df, coords = c("lon", "lat"), crs = 4326)
df.rs <- df_sf %>%
  st_join(rs.sf, join = st_nearest_feature, left = T) #%>%
  #slice_sample(n = 100) %>%
  select(main_riv)

as_tibble(df.rs) %>%
  distinct(main_riv)

plot_map_Nord +
  geom_sf(data = rs.sf) +#, aes(fill = geom)) 
  geom_sf(data = df.rs, size = 0.2, color = "red")+#, aes(fill = geom)) 
  theme_bw()

```


## Build spatiotemporal temperature data

```{r}
# For using the modelled E-Hype data
# library(ncdf4) # tidync not working on the hype netcdf (cant find the catchment id:s). Note this is only one year. 
# nc <- nc_open("/Users/vitl0001/Documents/Projects/DIASPARA/Incoming data/wtemp_ymonmean_abs_E-HYPEcatch05-EUR-11_ICHEC-EC-EARTHcatch_v1/wtemp_ymonmean_abs_E-HYPEcatch01-EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_CLMcom-CCLM4-8-17-v1_na_1971-2000_catch_v1.nc")
# 
# ds   <- ncvar_get(nc, "id")   
# times <- ncvar_get(nc, "time") 
# temps <- ncvar_get(nc, "wtemp_ymonmean")
# 
# nc_close(nc)
# 
# df_tidy <- expand_grid(id = ids, time_raw = times) %>%
#   mutate(
#     wtemp = as.vector(temps), # This unrolls the matrix to match the grid
#     date = as.Date("1971-01-01") + time_raw 
#   )
# 
# # Shape files for catchments
# catchments_sf <- st_read("/Users/vitl0001/Documents/Projects/DIASPARA/Incoming data/EHYPE3_subbasins")
# 
# glimpse(catchments_sf)
# 
# cthtemp <- catchments_sf %>%
#   inner_join(df_tidy, join_by(SUBID == id))
# 
# cthtemp %>%
#   filter(date == "1971-01-01") %>%
#   ggplot() +
#   geom_sf(aes(fill = wtemp, color = NA)) +
#   scale_fill_viridis_c()


# For the gridded landsat 5 data
library(tidync,tidyterra)
dft <- tidync("/Users/vitl0001/Documents/Projects/DIASPARA/Incoming data/data_stream-moda.nc") %>%
  hyper_tibble()

dft_m <- dft %>%
  select(-lblt) %>%
  mutate(year = as.numeric(str_sub(valid_time,start = 1, end = 4))) %>%
  mutate(across(c(longitude, latitude), ~ as.numeric(.))) %>%
  summarise(mean_temp = mean(lmlt) -273.15, .by = c(longitude, latitude, year))

dft_m %>%
  filter(year %in% c(1975,1995,2015,2025)) %>%
  ggplot() +
  geom_raster(aes(x = longitude, y = latitude, fill = mean_temp)) +
  facet_wrap(~year) +
  theme_minimal() +
  scale_fill_viridis_c()

# dft_rast <- dft_m %>%
#   pivot_wider(names_from = year, values_from = mean_temp) %>%
#   tidyterra::as_spatraster(crs = "EPSG:4326")
# 
# d_ca_sf <- ca_sf %>%
#   select(1:14)
# # extract temperature to ca_sf fr
# ca_amtemp <- terra::extract(dft_rast, d_ca_sf, fun = mean, na.rm = TRUE, ID = TRUE)
# ca_amtemp <- ca_amtemp[complete.cases(ca_amtemp), ] %>%
#   left_join(d_ca_sf %>% mutate(ID = row_number()), by = "ID") %>%
#   st_as_sf()
#   
# mb_amtemp <- ca_amtemp %>%
#   #slice_head(n = 1000) %>%
#   pivot_longer(
#     cols = matches("^\\d{4}$"), # columns that are exactly 4 digits
#     names_to = "year",
#     values_to = "temp"
#   ) %>%
#   group_by(main_bas, year) %>%
#   summarise(mb_temp = mean(temp), .groups = "drop")

plot_map_Euro +
  geom_sf(data = mb_amtemp %>% filter(year %in% c(1975,2025)), 
          aes(fill = mb_temp), color = NA) +
    scale_fill_viridis_c(name = "Temp (°C)") +
  facet_wrap(~year)

```

## Join in temperature data 
```{r}
sallaa.sf <- st_as_sf(sallaa %>% drop_na(lat,lon), coords = c("lon", "lat"), crs = 4326)
 st_crs(sallaa.sf)
# st_crs(ca.amtemp)

salf.sf_t <- sallaa.sf %>%
  filter(age.type == "juve.only") %>%
  # ggplot() +
  # geom_sf()
  st_join(mb_amtemp, join = st_within, left = TRUE) %>% 
  filter(year.x == year.y) 

plot_map_Euro +
  geom_sf(data = salf.sf_t, aes(color = mb_temp))
  
salf.sf_t %>%
  ggplot(aes(x=mb_temp,y=length_mm, group = factor(tot.age))) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~tot.age)
```

# refbast
```{r}

# I am using a database on spatai characteristics (shape files) based on parquet files with a directory structure with a main directory with  three different spatial featrues and shapefile in three subdirectories. each feature subdirectory has regional subdirectories. I am using the arrow-package and R-studio to retain information from the shapefiles to my data based on nearest neighbour spatial joins. How can i use 


refbast <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/refbast/refbast_tr_area_are_polygon.parquet", format = "parquet")
refbast <- open_dataset("/Users/vitl0001/Documents/Projects/DIASPARA/Habitat_db/refbast/refbast_landings_wbast_river_names.parquet", format = "parquet")

refbast %>%
  collect() %>%
  select(are_code,are_lev_code,are_wkg_code,are_name) %>% collect()

class(rb.df$geom_line) # not compatible with sf 
#"As for geom_line, it is a known issue with parquet files. When converting the data from psql to parquet I can only register one column as a geometry, hence the other one being a chr. I’ll add a second file where geom_line is the main geometry later on so you’ll be able to merge both files and have geom_polygon and geom_line working." /Jules

rb.df.sf <- rb.df %>%
  drop_na(geom_polygon) %>%
  mutate(geometry = st_as_sfc(geom_polygon, EWKB = TRUE, crs = 4326)) %>%
  st_as_sf(sf_column_name = "geometry") 

rb.df.sf %>% filter(are_lev_code == "River") %>%
  ditinct(are_name)

ggplot() +
  geom_sf(data = rb.df.sf %>% filter(are_lev_code == "River"))


plot_map_Euro +
  geom_sf(data = rb.df.sf %>% filter(are_lev_code == "River"))

sal.df <- readRDS(file = paste0(home,"/data/data-for-2-2/salmon-laa_2025-12-21.RData")) 

sal.df %>% 
  geom_sf(data = rb.df.sf %>% filter(are_lev_code == "River"))
  
```
